Description of MBCindices_Ndj
Home > STAS-WPP > STAS-Aeroelastic > MBCindices_Ndj.m
MBCindices_Ndj
PURPOSE
SYNOPSIS
function [b1,b2,b3] = MBCindices_Ndj (Ndj,idofs)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MBCindices
aeroPower
buildD42observer
closedLoopD42
generateOLTfromCLT
generateStressTFs Get spectra of stresses from particular locations.
internalLoadSpectra Get spectra of internal loads at particular locations.
stressSpectra Get spectra of stresses from particular locations.
MBCOLT
runWind Generate turbulence spectra, including the effects of periodic
SOURCE CODE
function [b1,b2,b3] = MBCindices_Ndj (Ndj,idofs)
Ndb = idofs(7) - idofs(6);
ind = [1:Ndj].';
for ib = 1:3
   ii = zeros(Ndj,1);
   ii(idofs(5+ib)+[1:Ndb]) = 1;
   ii(Ndj-3+ib) = 1;
   ii = logical(ii);
   if (ib == 1)
      b1 = ind(ii);
   elseif (ib == 2)
      b2 = ind(ii);
   elseif (ib == 3)
      b3 = ind(ii);
   end
end