Description of slaveDOFs
Home > STAS-WPP > STAS-Aeroelastic > slaveDOFs.m
slaveDOFs
PURPOSE
SYNOPSIS
function slv = slaveDOFs (idofs)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
aeroelastic
constraints function Lambda = constraints (qB,PB,Tbh,idofs,idofm)
initialDOFVelocity
structure
generateOLTfromCLT
getPsia
buildOpenLoopTurbine
SOURCE CODE
function slv = slaveDOFs (idofs)
slv = [idofs(2)+[1:6] idofs(3)+[1:6] idofs(4)+[1:6] idofs(5)+[1:3] ...
       idofs(6)+[1:6] idofs(7)+[1:6] idofs(8)+[1:6]].';