Description of BTEfun
Home > STAS-WPP > STAS-Main > BTEfun.m
BTEfun
PURPOSE
SYNOPSIS
function [dxdt,A] = BTEfun (x,yin,params);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
buildTurbineElectric
This function is called by:
generatorEfficiency Run a set of steady-state calculations of generator efficiency, which is
asymWind Run a Newton's method solution of the closed-loop turbine, and check the
SOURCE CODE
function [dxdt,A] = BTEfun (x,yin,params);
[dxdt,yout,A,B,C,D] = buildTurbineElectric (1,x,yin,params);