Description of inductance
Home > STAS-WPP > STAS-Electric > inductance.m
inductance
PURPOSE
SYNOPSIS
function [L,dL] = inductance (I0,L0,II)
DESCRIPTION
 Saturation effects in magnetic components are represented by a
 nonlinear effective inductance, that at any given point is the tangent
 of the terminal voltage versus rate-of-change-of-current curve.  This
 curve is represented by a spline.
 Version:        Changes:
 --------        -------------
 27.08.2018      Original code.
 Version:        Verification:
 --------        -------------
 27.08.2018      Checked sample test cases.
 Inputs:
 -------
 I0              : I's at which L's are given, four points.
 L0              : values of inductance at the I's.
 II              : currents at which to compute L.
 Outputs:
 --------
 L               : effective value of inductance.
 dL              : = dL/dI.
CROSS-REFERENCE INFORMATION
This function calls:
splineCoefficients
splineSMatrix
This function is called by:
PMSG
Transformer
converterControlGen
converterControlNet
generateCpCtTables
generatorEfficiency Run a set of steady-state calculations of generator efficiency, which is
STASControl_DTU10MW
STASElectric_DTU10MW
STASPitch_DTU10MW
STASSensor_DTU10MW
STASTurbine_DTU10MW -------------------------------------
STASYaw_DTU10MW
TCD42
TCD42Lin y vector: u vector:
TCD42grid Newton-Raphson solution of the TC RWP grid with turbines, and
asymWind Run a Newton's method solution of the closed-loop turbine, and check the
buildD42observer
closedLoopD42
generateOLTfromCLT
generateStressTFs Get spectra of stresses from particular locations.
internalLoadSpectra Get spectra of internal loads at particular locations.
linkobs
linkplantcontrol
stressSpectra Get spectra of stresses from particular locations.
getLTMnorms
runWind Generate turbulence spectra, including the effects of periodic
SOURCE CODE
function [L,dL] = inductance (I0,L0,II)
%
% Saturation effects in magnetic components are represented by a
% nonlinear effective inductance, that at any given point is the tangent
% of the terminal voltage versus rate-of-change-of-current curve.  This
% curve is represented by a spline.
%
% Version:        Changes:
% --------        -------------
% 27.08.2018      Original code.
%
% Version:        Verification:
% --------        -------------
% 27.08.2018      Checked sample test cases.
%
% Inputs:
% -------
% I0              : I's at which L's are given, four points.
% L0              : values of inductance at the I's.
% II              : currents at which to compute L.
%
% Outputs:
% --------
% L               : effective value of inductance.
% dL              : = dL/dI.
L = zeros(size(II,1),1);
dL = zeros(size(II,1),1);
[A,B] = splineCoefficients (I0);
[S,dSdx] = splineSMatrix (I0,II);
Am1BL0 = A\(B*L0);
L = S*Am1BL0;
dL = dSdx*Am1BL0;