Description of absc
Home > STAS-WPP > STAS-Utilities > absc.m
absc
PURPOSE
SYNOPSIS
function z = absc(x)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BEMNL
ClCdCm
bodyModes
modes
speedyBEM2
magOffDiag Get the magnitudes of each skew-symmetric off-diagonal pair.
SOURCE CODE
function z = absc(x)
ind = (real(x) < 0);
z = x;
z(ind) = -x(ind);