Description of getLTMnorms
Home > STAS-WPP > STAS-Utilities > getLTMnorms.m
getLTMnorms
PURPOSE
SYNOPSIS
function [length,time,mass,current,voltage,velocity,force,power,stress,ndens,nvisc,stiffness,damping,resistance,inductance,capacitance,flux] = getLTMnorms (fname)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
inductance
This function is called by:
generatorEfficiency Run a set of steady-state calculations of generator efficiency, which is
STASControl_DTU10MW
STASPitch_DTU10MW
STASSensor_DTU10MW
STASYaw_DTU10MW
TCD42
TCD42Lin y vector: u vector:
TCD42grid Newton-Raphson solution of the TC RWP grid with turbines, and
asymWind Run a Newton's method solution of the closed-loop turbine, and check the
buildD42observer
closedLoopD42
generateOLTfromCLT
generateStressTFs Get spectra of stresses from particular locations.
internalLoadSpectra Get spectra of internal loads at particular locations.
linkobs
linkplantcontrol
stressSpectra Get spectra of stresses from particular locations.
runWind Generate turbulence spectra, including the effects of periodic
SOURCE CODE
function [length,time,mass,current,voltage,        ...
          velocity,force,power,stress,ndens,nvisc, ...
          stiffness,damping,resistance,inductance, ...
          capacitance,flux] = getLTMnorms (fname)
load(fname);
length      = LTMnorms(1);
time        = LTMnorms(2);
mass        = LTMnorms(3);
current     = LTMnorms(4);
velocity    = length/time;
force       = mass*length/(time^2);
power       = force*velocity;
stress      = force/(length^2);
ndens       = mass/(length^3);
nvisc       = mass/(length*time);
stiffness   = force/length;
damping     = force*time/length;
voltage     = power/current;
resistance  = voltage/current;
inductance  = voltage*time/current;
capacitance = current*time/voltage;
flux        = voltage*time;