Description of maxc
Home > STAS-WPP > STAS-Utilities > maxc.m
maxc
PURPOSE
SYNOPSIS
function z = maxc (a,b)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BEMNL
BEMinit
aoadyn
prandtl
cpvwb
Transformer
converterControlNet
fbem
speedyBEM2
SOURCE CODE
function z = maxc (a,b)
ind = (real(a) < real(b));
z = a;
z(ind) = b(ind);