Description of minc
Home > STAS-WPP > STAS-Utilities > minc.m
minc
PURPOSE
SYNOPSIS
function z = minc (a,b)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BEMNL
BEMinit
aoadyn
fbem
asymWind Run a Newton's method solution of the closed-loop turbine, and check the
starBlock
SOURCE CODE
function z = minc (a,b)
ind = (real(a) > real(b));
z = a;
z(ind) = b(ind);