Description of spinToVec
Home > STAS-WPP > STAS-Utilities > spinToVec.m
spinToVec
PURPOSE
SYNOPSIS
function vec = spinToVec (sp)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
d2mudq2
dmudq
getMu
SOURCE CODE
function vec = spinToVec (sp)
vec = zeros(3,1);
vec(1) = 0.5*(sp(3,2) - sp(2,3));
vec(2) = 0.5*(sp(1,3) - sp(3,1));
vec(3) = 0.5*(sp(2,1) - sp(1,2));