Description of TFromTheta
Home > STAS-WPP > STAS-Utilities > TFromTheta.m
TFromTheta
PURPOSE
SYNOPSIS
function T = TFromTheta (th)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
vecToSpin
This function is called by:
BEMprepTransforms
FRefMatrix Version: Changes:
Qgnod
Qunod
aeroPower
airfoilToRotor
angularVelocity
constraints function Lambda = constraints (qB,PB,Tbh,idofs,idofm)
d2Qudq2
d2mudq2
dQgdq
dQudq
derivConstraints
derivElementCS
dmudq
elementCSFromNodes
genSpeed
getMu
globalPosLin
globalPosition
jointTorque
projectElement
projectElements
rotorSpeedAero
secondDerivElementCS
soilLin
soilNL
soilPower
generateCpCtTables
appliedPower
asymWind Run a Newton's method solution of the closed-loop turbine, and check the
buildD42observer
closedLoopD42
generateOLTfromCLT
getPsia
buildClosedLoopTurbine
buildOpenLoopTurbine
buildSij
periodicWind
SOURCE CODE
function T = TFromTheta (th)
TTH = vecToSpin (th);
T = expm (TTH);