Description of vecToSpin
Home > STAS-WPP > STAS-Utilities > vecToSpin.m
vecToSpin
PURPOSE
SYNOPSIS
function sp = vecToSpin (vec)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
d2Tdth2
d3Tdth3
dTdth
TFromTheta
SOURCE CODE
function sp = vecToSpin (vec)
sp = [0 -vec(3) vec(2);vec(3) 0 -vec(1);-vec(2) vec(1) 0];